### PR TITLE
add reported shootings data

### LINKED ISSUE #1: add reported shooting data
https://data.cincinnati-oh.gov/safety/CPD-Reported-Shootings/sfea-4ksu/about_data

- data is recorded as "1200 Block of Main Street"
- replace last 2 digits with "X" and remove "Block of" then use street range matching functions

### PR DESCRIPTION
**Pull request by erikarasnick**

### CODE REVIEW

**Comment by erikarasnick** [comment]
length of range? 
how many matched vs. unmatched?

**Comment by erikarasnick** [comment]
updates: 
- using `addr::addr_match_tiger_street_ranges` with arguments `street_only_match = "closest"` and `summarize = "union"` to return one street range geometry per row (closest street range when the street number does not fall within any available ranges, and unionized geometries when matched to more than one street range)
- appended dummy address components to both TIGER street range addresses and reported shooting addresses to have street number, street name/type, city, state, zip

- only 84/1484 reported shootings remain unmatched to any street range. about 25% of these are interstates or some other designation that does not align with street ranges (e.g., "district 4", "unknown location")

ideas for evaluating matched street ranges and "off the shelf" jittered lat/lon:
- length of matched street range geometries
- distance between matched street range and jittered point

**Comment by erikarasnick** [comment]
lengths seem reasonable 

```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  20.56   99.88  162.24  206.14  270.85 1123.89 
```

**Comment by erikarasnick** [comment]
@cole-brokamp release new version of `xx_address` repository after merging in new versions of `crime_incidents`, `shotspotter`, and `reported_shootings` ?

**Review by cole-brokamp — APPROVED** [review]

**Comment by cole-brokamp** [comment]
> @cole-brokamp release new version of `xx_address` repository after merging in new versions of `crime_incidents`, `shotspotter`, and `reported_shootings` ?

Yes, sounds like a good idea.

**Comment by cole-brokamp** [comment]
> > @cole-brokamp release new version of `xx_address` repository after merging in new versions of `crime_incidents`, `shotspotter`, and `reported_shootings` ?
> 
> Yes, sounds like a good idea.

actually no

**Pull request merged**
